version: "3"
services:

  api:
    build:
      context: ./node
      target: production
    container_name: api
    restart: on-failure
    privileged: true
    volumes:
      - ./node:/app/
    ports:
      - "8000:8000"
    # volumes:
    #   - /sys/devices/platform/soc/3f200000.gpio:/sys/devices/platform/soc/3f200000.gpio
    #   - /sys/class/gpio:/sys/class/gpio
    env_file:
      - .env

  ui:
    container_name: ui
    build:
      context: ./ui
      target: production
    restart: on-failure
    volumes:
      - ./ui:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - api

volumes:
  container-data:

networks:
  default:
    name: runttare_network
