version: "3"
services:

  api:
    build:
      context: ./node
      target: production
    container_name: api
    restart: on-failure
    privileged: true
    volumes:
      - ./node:/usr/src/app
      - ./runtta.db:/usr/src/app/dist/runtta.rb
      - /usr/src/app/dist/
      - /usr/src/app/node_modules/
    ports:
      - "8000:8000"
    # volumes:
    #   - /sys/devices/platform/soc/3f200000.gpio:/sys/devices/platform/soc/3f200000.gpio
    #   - /sys/class/gpio:/sys/class/gpio
    environment:
      - "RUNTTA_TIMEOUT=3000"
      - "RUNTTA_STATUS_PIN=3"
      - "RUNTTA_PISTON_PIN=3"

  ui:
    container_name: ui
    build:
      context: ./ui
      target: production
      args:
        API_URL: http://runttare.local:8000/runtta
        BROKER_URL: ws://runttare.local:8000/ws
    restart: on-failure
    volumes:
      - ./ui:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - "80:80"
    environment:
      - "REACT_APP_API_URL=http://runttare.local:8000/runtta"
      - "REACT_APP_BROKER_URL=ws://runttare.local:8000/ws"
    depends_on:
      - api

volumes:
  container-data:

networks:
  default:
    name: runttare_network
